<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>69c68c88-09a9-46ad-b46f-51ee237d8eff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.text-capitalize.font-weight-bold.px-10.v-btn.v-btn--is-elevated.v-btn--has-bg.theme--dark.v-size--large</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b148cdd-3ee6-48e4-9247-37d9b4a4f1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ffe6a39f-3848-4ceb-9e93-daf5da2bb007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-capitalize font-weight-bold px-10 v-btn v-btn--is-elevated v-btn--has-bg theme--dark v-size--large</value>
      <webElementGuid>765196c6-3236-45a6-8493-7eca3d7f908a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Add
        </value>
      <webElementGuid>351942b0-eb42-4d4a-916a-c685f906c540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container pa-4 pa-md-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-12&quot;]/form[1]/button[@class=&quot;text-capitalize font-weight-bold px-10 v-btn v-btn--is-elevated v-btn--has-bg theme--dark v-size--large&quot;]</value>
      <webElementGuid>e5077c1e-f237-4a0c-a07b-e16368108caa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>da1c2aa3-e36c-46de-9373-ad8071b90ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/button</value>
      <webElementGuid>6a6f69c0-23fb-4ea1-baaf-ec08a339c307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Image'])[1]/following::button[1]</value>
      <webElementGuid>fb69dc43-87cc-492c-b6e0-efffcdae007f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::button[1]</value>
      <webElementGuid>772aaf31-0640-4b4f-ae31-5dd8c9034623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>468fa933-d14d-405c-bb20-4e5dd3033906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
          Add
        ' or . = '
          Add
        ')]</value>
      <webElementGuid>00726687-81ca-41bc-a681-ab245a609467</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
