<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_input-130</name>
   <tag></tag>
   <elementGuidId>963bb0b1-f2e6-4e9a-8420-53b6a000087a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-130</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-130']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f96125f4-7e55-45a2-9c4e-cab4ea2acb4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ac1f794a-05c0-4c3a-abd3-2cdf7497d9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-130</value>
      <webElementGuid>62a3e2c0-9c41-4b9a-b380-189487afd1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What is the name of this category?</value>
      <webElementGuid>2a63f967-5c31-4595-9e78-c65061094818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7598a1c7-3fb0-4106-9130-8adbb3fbb30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-130&quot;)</value>
      <webElementGuid>465f7149-6128-4cad-9d8d-efc7dba88114</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-130']</value>
      <webElementGuid>e06532d5-85d0-4c26-81f0-251a84ab3582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>4ba4998f-87f0-4e25-8d2f-37e192d4d2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>248793e0-f228-44b8-9999-9e2502a9de23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-130' and @placeholder = 'What is the name of this category?' and @type = 'text']</value>
      <webElementGuid>e761da6a-a85e-4d8a-96f4-4e7362ae479f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
