<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-13 (1)</name>
   <tag></tag>
   <elementGuidId>d2337586-db5e-4df7-8fda-06bc90538f5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-13']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>210ed755-8cc4-48aa-8149-61f2d3ac1b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>064db2fb-f4a9-4951-bea3-4e27e1359740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-13</value>
      <webElementGuid>a9a95dee-47b8-482a-8711-4fb279b4a2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email!</value>
      <webElementGuid>177abfb6-61c2-4937-87ff-06ad7e0e9915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb4f05ea-fbba-45f7-963e-cc92f038c20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-13&quot;)</value>
      <webElementGuid>0573a2b0-e12c-4f6c-b3da-dc98452bbe0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-13']</value>
      <webElementGuid>9f9552fe-b361-4e2a-9a76-7938d8b574f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>1e5f4f13-5f75-4d8c-87bc-ad4ea3d4956e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>873bca67-178e-426a-80b9-5aed21ace624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-13' and @placeholder = 'Enter your email!' and @type = 'text']</value>
      <webElementGuid>483bb2bd-a206-47a0-8e1d-fe33ca731ce8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
