<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-16 (1)</name>
   <tag></tag>
   <elementGuidId>17e4bae3-efd3-4499-8db7-9dc7543d61d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-16']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a7ee151-1173-4b9b-8a5b-f36b4ec25a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>229b887e-4f4e-4ae2-a771-0e0804822fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-16</value>
      <webElementGuid>a43d63f7-1e80-404d-964a-e2f324122294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your password!</value>
      <webElementGuid>d3dd6e37-812a-455e-be2d-ace6d4e1dc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ef96f9ae-d6f2-4c3f-bfb0-c19705d66709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-16&quot;)</value>
      <webElementGuid>3af02f98-6e68-4846-8bcc-b862b58cf784</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-16']</value>
      <webElementGuid>0d187082-9fff-4632-b7ba-b7dc2a209d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div/form/div[4]/div/div/div/input</value>
      <webElementGuid>43425191-669a-4c69-8f0f-dc8e0882dfde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>322acb5c-4962-4670-847b-820fd83ea3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-16' and @placeholder = 'Enter your password!' and @type = 'password']</value>
      <webElementGuid>d02cb2c8-3128-4e42-9266-2b20de760639</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
