<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-16 (2)</name>
   <tag></tag>
   <elementGuidId>4440c277-b023-4457-8b32-60fd3072d6cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-16']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ed0c16f-fc3a-4b8a-aa0a-2013c0793238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f0e155e6-783b-4ce6-8666-20038052ecd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-16</value>
      <webElementGuid>e853b230-3c84-41d4-8016-c66a05a78a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your password!</value>
      <webElementGuid>abc2e898-0a5f-4a99-a1e3-68f23c63b2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f79cf966-d698-4678-9efc-723fa1b419c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-16&quot;)</value>
      <webElementGuid>e5289082-b346-492d-a87e-f0b46b33cec8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-16']</value>
      <webElementGuid>dc806909-61e6-4f6f-badd-61f160dab1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div/form/div[4]/div/div/div/input</value>
      <webElementGuid>f45adecd-2007-44d7-8b4d-3766568e5dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>2de6ab2f-7f8d-467e-8f96-3e967f240fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-16' and @placeholder = 'Enter your password!' and @type = 'password']</value>
      <webElementGuid>af997bc0-7776-45cb-b8bf-48633aa10c8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
