<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Overview_v-overlay__scrim</name>
   <tag></tag>
   <elementGuidId>32921a5d-a045-4261-b070-b02ff8390ab7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-overlay__scrim</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>25d23468-218a-4f74-b6f9-d45661f87333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-overlay__scrim</value>
      <webElementGuid>50c184fe-a588-4938-a2a9-c816330efb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-overlay v-overlay--active theme--dark&quot;]/div[@class=&quot;v-overlay__scrim&quot;]</value>
      <webElementGuid>00bfea9a-e7fa-4fa0-866c-d3a79435e723</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div</value>
      <webElementGuid>11e77776-3ba0-46ad-aa38-aaacfad0e66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>f1fc862c-9a91-4e44-a6f6-3d26b345feb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
